### ISSUE TITLE
Refactor Launcher branding to BrawlBack instead of Slippi

### ISSUE THREAD

**Issue by JaredWhiteOne** [Brawlback-Team/brawlback-asm#50]

**Comment by Jching83** [comment]
I needed to get some clarification. Are you just wanting to change everything name Slippi to Brawlback?

**Comment by JaredWhiteOne** [comment]
@Jching83 There's also various images, icons, naming conventions, etc. that need to be decoupled from Slippi and Melee as a whole. The list of exact things that need to be changed is exhaustive, but I can produce some examples as needed.

**Comment by JaredWhiteOne** [comment]
Closing as I have an issue on the launcher repo (made this on mistake)
